### ISSUE TITLE
Sprite Color errors

### ISSUE THREAD

**Issue by miketrethewey** [Zarby89/Enimizer#1]
I'm aware that we've got palette randomization as part of the scope of the project.

Small hearts under pots seem to be subject to it and should probably stay their default color scheme.

- [x] Small Hearts
- [x] Rupees
- [x] Shop contents

**Comment by miketrethewey** [comment]
Rupees are subject to altered palettes it seems. Makes me panic when I'm getting ones that are green in color but are in fact providing the proper amount.

**Comment by miketrethewey** [comment]
- [ ] Small Hearts
- [ ] Rupees
- [ ] Shop contents

**Comment by Zarby89** [comment]
fixed, all absorbables items will keep their original palette
