### ISSUE TITLE
[Question] Potential for softlocks, possible?

### ISSUE THREAD

**Issue by Ammako** [Zarby89/Enimizer#10]
Hey, I'm wondering, does Enemizer properly take everything into account to make sure random dungeon enemies can't possibly cause softlocking?

I am aware that sometimes the enemizer places stuff like Beamos in the most inopportune of places, requiring you to damage boost through them to get past them, and this is fine with me, that's part of the strategy of getting through those areas, but there are other things that made me scratch my head a little bit in wonder.

For example, in the run I was doing the other day, the switch in the main room of Mire was randomized under a different pot, which is fine, but a moveable statue was spawned on top of the pot. It isn't possible to move those statues when they're on top of a pot, and it's not possible to lift the pot while the statue is on there, so the only way I could figure out to access that pot was to smash it with the hammer, through the statue. This allowed me to then push the statue and step on the switch, but it also made the hammer a hard requirement for accessing this switch (unless I'm dumb and there was another way to move the pot or the statue that didn't require the hammer, in which case I'm interested in knowing :p)

That chest ended up being the compass or something dumb like that, but if it had been the big key or something, then hammer would have been an additional requirement for mire altogether, which would have been a problem if the hammer was on mire boss/big chest (or even in that particular chest), maybe also if hammer was in fat fairy's cave with Mire having crystal 5 or 6.

Picture to show what I'm talking about: http://i.imgur.com/E63iqZk.png
That pot had the switch under it, and the bunny beam got randomized into a moveable statue. I know it's possible to lift pots while moveable statues are partially onto them, like we do in Swamp Palace, but in my case the statue was fully on top of the pot, + I could only really access the pot from the left/right so i had fewer angles to try and lift the pot from which might not have helped. Statue wouldn't move an inch either no matter what I tried, until I smashed the pot away.

If there's already checks to prevent that kind of thing from happening then it's all good, I just figured I'd ask about it because this kind of thing seems a bit odd to me, and with the wide variety of entities that can be shuffled around, I figured it was possible that there could be weird interactions like this that flew past the radar. :p it's probably a fairly rare occurrence.

**Comment by Zarby89** [comment]
There's probably lots of ways to softlock in enemizer unfortunately that's why it require more testing :) i can't think of anything like that kind of thing haha, thanks for the screen i'll add a condition for that sprite it should not happen if it require the hammer because hammer could be at vitreous for example... 

the only logic check actually are preventing kholdstare, trinexx, arrghus to have an item if they are not in their original dungeons, or if the fire rod, ice rod, hookshot is in ganon tower, also some statue should not spawn in water room or some small corridor rooms to prevent softlock but yeah thanks for reporting it 👍 

i'm fixing them one by one when i get report like that, same for the gfx glitches remaining :)

**Comment by Ammako** [comment]
Well I'll be happy to run Enemizer more often and keep a look out for that kind of thing. I'll let you know if I come across anything else that has potential for softlocking.

If I have to abandon a seed because of something like this then oh well, not that big of a deal and at least it will have helped :p I'll still be having fun and enjoying Enemizer.

**Comment by Ammako** [comment]
On that note, would you prefer to have a new github issue opened for every softlock, or have one centralized thread where everything goes so it doesnt create too many report threads?

**Comment by Zarby89** [comment]
Well anywhere is fine i don't really mind i don't think there's a lots of ways to softlock anymore anyways, i patched most of them
