### ISSUE TITLE
Mothula in Turtle Rock Damage Bug

### ISSUE THREAD

**Issue by miketrethewey** [Zarby89/Enimizer#11]
iBazly had an issue fighting Mothula in Turtle Rock. Immune to Tempered Sword slashes but vulnerable to Fire Rod shots.
Maybe it has something to do with Trinexx' shell on the ground or the properties of that sector of the super room.
[Twitch Clip](https://clips.twitch.tv/FuriousYawningStrawberryPanicBasket)

**Comment by Zarby89** [comment]
Mothula can't be attacked with slashes / spin with the golden sword only poke, it a vanilla "feature" :P , i don't plan on patching it, the randomizer is patching it for mothula room but it should be easy enough to poke mothula in the others rooms, also the tempered sword slashes work but the tempered spin attack won't work
