### ISSUE TITLE
Ice Palace Tongue Pull Glitch

### ISSUE THREAD

**Issue by EnderofGames** [Zarby89/Enimizer#21]
I apologize if it is not the _Enemizer_ causing this problem, but I have rarely ran into this problem and I believe it is caused by the enemy randomization somehow: 

The "_last chest_" you get to in Ice Palace, as little of a name I have for it, which I believe the item randomizer calls "_[dungeon-D5-B5] Ice Palace - b5 up staircase_" has a tongue-activated door to go back towards the boss-area of the dungeon. When using _Enemizer_, this tongue sometimes pulls, makes a Zelda-Unlock noise, but does not open the door. 

In this image, the tongue is pulled, but the door that link is looking at should be open: 
<img width="753" alt="tongue no work" src="https://user-images.githubusercontent.com/17417666/30777364-feb2eeb0-a075-11e7-9a9a-72d6126c86f3.PNG">

This is not a softlock, nor a "Save & Quit" lock, as there is an exit above that is not preferred for time or enemies. It has happened in about one in five (20%) of all _Enemizers_ I have seen or watched. Occasionally, though possible anecdotal, I see what looks like a changed sprite in the tongue-statue during transition. 

If a ROM with this glitch occurring is wanted or needed, I can upload it, just ask.

**Comment by sosuke3** [comment]
This appears to be caused by statues in the same super room. Statues will be excluded from this room in the next version.
