### ISSUE TITLE
Impassable rooms due to enemies

### ISSUE THREAD

**Issue by miketrethewey** [Zarby89/Enimizer#26]
Spike Trap in Ice Palace (Floor B5) as reported by Ender of Games
![image](https://user-images.githubusercontent.com/2232440/31579713-d7f5ae08-b0f0-11e7-98ce-2722c0167f83.png)

**Comment by sosuke3** [comment]
Need to add this room to do not randomize list for guruguru bar, or need to exclude spikes

**Comment by sosuke3** [comment]
Excluded a variety of sprites from the room for now. Please let me know if anything ever shows up that causes a problem.
