### ISSUE TITLE
Enemy Zone Blacklists

### ISSUE THREAD

**Issue by miketrethewey** [Zarby89/Enimizer#3]
The Geldman enemy may want to be restricted to sandy zones like Desert and Desert Palace since they emerge from the ground and look like sand.
![image](https://cloud.githubusercontent.com/assets/2232440/25316368/ddbdda4a-281a-11e7-82ac-fbb58f443ca9.png)

**Comment by miketrethewey** [comment]
Same with Devalant
![image](https://cloud.githubusercontent.com/assets/2232440/25317518/0b726d66-282f-11e7-91d7-60e759b55326.png)

**Comment by miketrethewey** [comment]
Had a push statue show in Spiral Cave.
And a Beamos in the staircase to the top of Light World East Death Mountain.

**Comment by miketrethewey** [comment]
Miketheviewer found a firebar in place of Black Ball & Chain trooper in Escape, not allowing collection of Big Key to get "Chest next to Zelda."

**Comment by Zarby89** [comment]
The geldman and devalant are fine in others area too, i don't want to add too many restricitions on what can be where, same for the statue in spiral cave this is annoying but do not cause any troubles, about that beamos i can't really do anything i won't add special handling for every single sprites to not be a specific sprites find some heart of safety items and damage boost throught them :p , and i fixed the firebar
