### ISSUE TITLE
Not able to randomize bosses in certain seeds

### ISSUE THREAD

**Issue by EnderofGames** [Zarby89/Enimizer#32]
_Using Enemizer v6.0, both original download on the discord with Pug changed to pug and latest download to test_

When attempting to generate a seed with _Bosses > Randomize Bosses_ checked off will cause the Enemizer to freeze for an indefinite amount of time, and upon clicking anywhere will close due to "Not Responding"

<img width="471" alt="no respond" src="https://user-images.githubusercontent.com/17417666/31752595-f5b3514c-b448-11e7-9d3c-13bd182c9c52.PNG">

Changing the _Type of Randomization_ does not alter this issue, always crashes when checked, always works while unchecked. 

So far I have found these files to crash:
ALttP - VT_no-glitches-26_normal-open-triforce-hunt_triforce-hunt_750028925
ALttP - VT_no-glitches-26_normal-open-triforce-hunt_triforce-hunt_872136068

**Comment by sosuke3** [comment]
Should be fixed by #33 
Please let me know if any other seeds ever cause this issue
