### ISSUE TITLE
Bugs Involving Enemies in the Last Room of Swamp Palace

### ISSUE THREAD

**Issue by EnderofGames** [Zarby89/Enimizer#35]
In the last room of Swamp Palace (pre-boss, of course) there is seven enemies: 

- Four red blob/slime enemies that "pop out of the ground", three below the entrance, one in a "pot storage room" visible from the entrance. 

- Three Water Tektite/"Striders"/"Skeeters" in the moving water in the lower half of the room. 

In the enemizer, this room, with exception, is filled with: 

1. Four enemies stuck in place, almost looking in all directions at once, where the blobs would be. 

Example: Two thieves stuck in place, a red anti-fairy (fidget spinner type) bouncing free, not bound like most other enemies, and one enemy missing, a castle guard that was also stuck in place. 
<img width="750" alt="swamp1" src="https://user-images.githubusercontent.com/17417666/31797059-85e7b10e-b4e9-11e7-831d-0b56953de1c9.PNG">

The anti-fairy is free of this bug, but other enemies prove impossible to get past, such as these thieves, and for no clear reason why. This would also likely make this room impossible for OHKO runs without Cape or Cane of Byrna. 

2. Three invisible enemies in the water where the Tektites should be. 

Example: When an invisible enemy overlaps Link you can see right through him.
<img width="753" alt="swamp2" src="https://user-images.githubusercontent.com/17417666/31797551-09abb326-b4ec-11e7-9f67-a759fa203c49.PNG">

The invisible enemies exhibit different abilities, such as the ability to squeak like sewer rats, but I can say that I have seen a single _flying stalfos head_ being pushed by the current against the wall. I don't know if the fact that it was against the wall is why I could see it, but I have also never _seen_ the Enemizer put other flying enemies or re-add skeeters to this location. (emphasis, seen, they may have been there before and I could not identify them.

**Comment by sosuke3** [comment]
This room should be fixed in the water section. The "land" section will get water sprites that might decide to return to their home planet.
