### ISSUE TITLE
Sprites Becoming "Garbled", Even When Enemies are Not Randomized. 

### ISSUE THREAD

**Issue by EnderofGames** [Zarby89/Enimizer#38]
Using Enemizer 6.0.04

While quite rare compared to actually randomizing enemies, seeds made by the _Enemizer_ sometimes mess up sprites when no randomizations are selected at all. 

To be clear, these are the Enemizer selections: 
<img width="470" alt="1" src="https://user-images.githubusercontent.com/17417666/31866222-9ca7f8fc-b739-11e7-94bd-ba482bfd1b8a.PNG">
<img width="470" alt="2" src="https://user-images.githubusercontent.com/17417666/31866223-9d1fa550-b739-11e7-96f5-735a9046babd.PNG">
<img width="470" alt="3" src="https://user-images.githubusercontent.com/17417666/31866224-9d3561e2-b739-11e7-8f6e-25d86aad5fa2.PNG">
<img width="470" alt="4" src="https://user-images.githubusercontent.com/17417666/31866225-9d488f10-b739-11e7-9ded-2e75b375b39a.PNG">

I used it on: 

> Enemizer 6.0.04 - ALttP - VT_no-glitches-26_normal-open-triforce-hunt_triforce-hunt_189603668 (EN229154905)

While looking for garbled sprites I usually go to PoD, Hera, Mire, and Thieves' Town. In this seed all enemies there were fine, but at Eastern sprites were messed up; "Bowling balls", both small and large, and Eyegores, both red and green. 
<img width="754" alt="no rando4" src="https://user-images.githubusercontent.com/17417666/31866262-4f8f712a-b73a-11e7-8368-5f9078701882.PNG">
<img width="752" alt="no rando5" src="https://user-images.githubusercontent.com/17417666/31866263-4fa5ef54-b73a-11e7-929f-89deafd22457.PNG">
<img width="752" alt="no rando6" src="https://user-images.githubusercontent.com/17417666/31866264-4fb8f69e-b73a-11e7-8479-0d0d2ae23575.PNG">
<img width="751" alt="no rando7" src="https://user-images.githubusercontent.com/17417666/31866265-4fcc9bae-b73a-11e7-9584-a60213628efc.PNG">

**Comment by EnderofGames** [comment]
A second example: 

> Enemizer 6.0.04 - ALttP - VT_no-glitches-26_normal-open-triforce-hunt_triforce-hunt_249595363 (EN4175499)

Mini Helmasaurs in the second room of Palace of Darkness:
<img width="752" alt="no rando8" src="https://user-images.githubusercontent.com/17417666/31866408-2cec7e90-b73c-11e7-970c-9afe88f69730.PNG">
Hardhat Beetles, reflecting their normal colour:
<img width="752" alt="no rando9" src="https://user-images.githubusercontent.com/17417666/31866409-2d040c18-b73c-11e7-9e6d-fdfca8cccd50.PNG">
Another Mini Helmasaur (facing downward, but it is the same sequence of garbled frames as the sprite) and falling tiles also appear strange:
<img width="752" alt="no rando10" src="https://user-images.githubusercontent.com/17417666/31866410-2d180cfe-b73c-11e7-9a6c-559db5ecf32e.PNG">

**Comment by sosuke3** [comment]
This should be fixed in 6.0.5
