### ISSUE TITLE
Sprite Construction errors

### ISSUE THREAD

**Issue by miketrethewey** [Zarby89/Enimizer#4]
In Swamp Dam, pull switches are jacked up.

Anti-Faeries seem to be messed up too.

**Comment by miketrethewey** [comment]
Hidden sprites for the statues that shoot fireballs.
![image](https://cloud.githubusercontent.com/assets/2232440/25317247/d5748852-2829-11e7-9258-4abb1c573828.png)

**Comment by miketrethewey** [comment]
Cannons on walls are garbled.

**Comment by miketrethewey** [comment]
Poes or Hues (ghosts with lanterns) seem to be floating spikes with sparkles.

**Comment by miketrethewey** [comment]
Eastern Palace cannonballs were hilarious, but, again, busted.

**Comment by miketrethewey** [comment]
Flying tiles in tile rooms.

**Comment by Zarby89** [comment]
the fireball sprite is hidden, the statue is only a tile, might have to reconsider them but i like them it more challenging, all canons / canonballs are fixed, ghosts can be flying crabs with sparkle, and also flying spikes with sparkle which is hilarious and should stay like that imo, all the 'special' sprites like tiles rooms, stalfos spawner, wizzrobes spawner, will be random
