### ISSUE TITLE
"Bush guards" commonly having garbled sprites

### ISSUE THREAD

**Issue by EnderofGames** [Zarby89/Enimizer#46]
Commonly, but not always, enemies found in bushes and grass have garbled sprites. This isn't limited to before or after defeating Agahnim I, and it seems that bush enemy in a "room" will always be the same, so it is either always garbled or always normal. This also seems to affect the pot guard that is occasionally found in the pot in Chicken House. 

An eyegore found in a bush in lost woods. 
<img width="423" alt="eyegore" src="https://user-images.githubusercontent.com/17417666/32140100-3f156482-bc1a-11e7-8e35-8c950067a68d.PNG">

This sprite seems harmless. It blocks shots, but not movement. However, two of them were found in the grass. 
<img width="752" alt="odd harmless" src="https://user-images.githubusercontent.com/17417666/32140121-ed674ae6-bc1a-11e7-9ba1-4efb7368fe0b.PNG">

A squirrel (Deadrock enemy) found South of Link's house, garbled in both its solid and normal forms
<img width="538" alt="squirrel" src="https://user-images.githubusercontent.com/17417666/32140152-cabd297e-bc1b-11e7-87dc-2db391eaf40e.PNG">

A normal bush guard post-defeat of Agahnim I, with similarly garbled tree leaves
<img width="752" alt="old garbles" src="https://user-images.githubusercontent.com/17417666/32140158-e73ec21a-bc1b-11e7-85e7-f238624d2ef2.PNG">

**Comment by EnderofGames** [comment]
I thought I saw that the plan was to stop the chicken under this pot from being randomized (until further notice). Perhaps that is why his sprite is messed up? It seems to always by a guard, never any other enemy. 
<img width="753" alt="under pot" src="https://user-images.githubusercontent.com/17417666/32140218-46c30834-bc1e-11e7-9709-cfe800d1689d.PNG">

**Comment by EnderofGames** [comment]
I thought I had pre-Agahnim I example, but it seems that the chicken house pot is alone on that one. This glitch might require defeating Agahnim I to reproduce. 

A thief found in a bush, made of a hinox head and a spazzing sprite on the bottom. 
<img width="750" alt="thief" src="https://user-images.githubusercontent.com/17417666/32140506-64136118-bc28-11e7-8abf-0837ab3cac55.PNG">

**Comment by Zarby89** [comment]
i think we found why it doing that, post agahnim use different sprites and we only have a table of 0x80 length it should be 0xC0 long to cover post agahnim sprites as well, the chickens in the pots are randomized even tho there's no place yet to set their gfx that should be fixed, and for the tree i have no clue to be honest hehe

**Comment by sosuke3** [comment]
Tree should be fixed in the next release

**Comment by EnderofGames** [comment]
Fixed in V6.0.12

(With the exception of the Raven, which has had problems longer than all of these enemies. Raven brought up in #56)
