### ISSUE TITLE
No Bosses spawning in Boss Rooms

### ISSUE THREAD

**Issue by Tojso** [Zarby89/Enimizer#7]

**Comment by Tojso** [comment]
Tried all LW dungeons, not one boss spawned in its boss room.

**Comment by Zarby89** [comment]
uh do you have a rom or something? that's seems to be impossible i don't touch any bosses rooms

**Comment by DarkCucco** [comment]
I had the same problem with Tower of Hera today

**Comment by zoro303** [comment]
I got the same as DarkCucco a moment ago.
No Moldorm in Tower of Hera. I wonder if it does this with every boss. Anyway, I just want to let you know about it.

**Comment by Zarby89** [comment]
i have removed the boss hp/damage randomization for now until i figure out a way it work :)

**Comment by Zarby89** [comment]
it had something to do with the hp/damage on bosses, should be fixed now i removed the randomization on bosses thanks :)
